### ISSUE TITLE
Users can create Syrian Desert Thunder Campaign, but it says Red Waters after clicking. 

### ISSUE THREAD

**Issue by adamclmns** [Kilcekru/dcc#11]
**Describe the bug**
When creating a new campaign, it is still possible to create a Desert Thunder Campaign, despite this being disabled.

**To Reproduce**
1 - Create a normal campaign, advance through to the Flight Groups screen. 
2 - Click "Campaign">"New Campaign" from the window menu.
3 - Click "Desert Thunder". You'll see the "Red Waters" campaign description displayed. click "Start Campaign". 
4 - Select desired Coalitions, I chose USA 2004 and Russia 1996
5 - Settings on the difficulty don't seem to matter, set what you like, and click "Next"
You'll now see a campaign on the Syria map, titled Desert Thunder

![image](https://github.com/Kilcekru/dcc/assets/1242662/51048de5-d493-4028-823a-a10b1b4a33b1)

**Expected behavior**
I don't think we're supposed to be able to select this option, and if we do, the screen following selection should reflect the Desert Thunder campaign selection instead of Red Waters. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - DCC Version N/A 

**Additional context**

**Comment by Kilcekru** [comment]
fixed
