### ISSUE TITLE
F-16C+A-10C missions always report with result "Killed in Action" despite successful landing and shutdown with no damage

### ISSUE THREAD

**Issue by okurz** [Kilcekru/dcc#123]
**Describe the bug**
F-16 missions always report with result "Killed in Action" despite successful landing and shutdown with no damage. I could report this so far 3 times with the F-16, one time with the A-10C, but not with the AV8B

**To Reproduce**
1. Start mission with F-16
2. Fly mission without loosing the plane
3. Land and shutdown
4. Submit results into DCC and observe the error

**Expected behavior**
The pilot should still be reported as "Alive"

**Screenshots**

![grafik](https://github.com/user-attachments/assets/8e37ef9b-27dd-4156-bee8-1db05f8207f5)

**Additional context**

DCC Version [v0.4.3-beta.2](https://github.com/Kilcekru/dcc/releases/tag/v0.4.3-beta.2)

From the logs I found

```
2024-07-31 11:26:40.625 ERROR   SCRIPTING (Main): Mission script error: [string "C:\Users\Oliver\AppData\Local\Temp\DCS\/~mis0000696E.lua"]:272: attempt to call field 'getName' (a nil value)
stack traceback:
	[C]: in function 'getName'
	[string "C:\Users\Oliver\AppData\Local\Temp\DCS\/~mis0000696E.lua"]:272: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>
```

just when I exited the runway. I stopped and shutdown the aircraft after that, ended the mission. The DCS internal log does not record that the airplane was damaged or destroyed in any way or that the pilot would be killed.

**Comment by Dragonius** [comment]
Line and error seams to be a cas.lua

There have  been some changes as DCS updated to 2.9.XXX Versions.

**Comment by okurz** [comment]
I can confirm that I can no longer reproduce the problem with [v0.4.4-beta.1](https://github.com/Kilcekru/dcc/releases/tag/v0.4.4.beta-1) and DCS 2.9.8.12140
