### ISSUE TITLE
Mission state issue

### ISSUE THREAD

**Issue by fullmetalfelix** [Kilcekru/dcc#125]
Regardless of how many times I am shot down in a multiplayer or singleplayer run, after submitting the mission state the human operated flights show up as "alive" and looks like the enemy shot down 0 planes, even if I have seen several friendly AI planes dropped.

**Comment by Dragonius** [comment]
do you have somewhere the "dcc_state.json"

**Comment by fullmetalfelix** [comment]
sorry not anymore. I setup a new campaign, with different planes and it seems all the shot-down planes are counted correctly. I'll keep the dcc_state.json next time I see the issue happening.

**Comment by Dragonius** [comment]
RECOMENT to close this isua @Kilcekru
