### ISSUE TITLE
Something went terribly wrong

### ISSUE THREAD

**Issue by Binary-System** [Kilcekru/dcc#2]
**Describe the bug**
Message "Something went terribly wrong" while having the campaign running without human participation

**To Reproduce**
Let the campaign run alone for 1+ days

**Expected behavior**
To continue the campaign

**Desktop:**

[dcc_support.zip](https://github.com/Kilcekru/dcc/files/11817855/dcc_support.zip)

**Comment by Kilcekru** [comment]
We identified the problem and fixed it.
The fix will be included in the next release v0.3.0
