### ISSUE TITLE
MP doesnt seem to work. Players cant join my server because of "module not found" error

### ISSUE THREAD

**Issue by nabbl** [Kilcekru/dcc#8]
**Describe the bug**
When I create a MP Server with the mission, other players cant join. They get an error message saying they need to buy specific modules. However I have no custom modules installed as far as I know. It works for example when I start a MP Mission with liberation.

**To Reproduce**
1. Start Mission as MP
2. Let other players join

**Comment by rhyver** [comment]
Can you please upload the "support zip" of your current campaign(Top Menu -> DCC -> About -> Create Support Zip)

**Comment by nabbl** [comment]
here you go
[dcc_support.zip](https://github.com/Kilcekru/dcc/files/12064345/dcc_support.zip)

**Comment by HighwaymanEd** [comment]
Having a very similar issue with a dedicated server myself. The mission starts on the server, but when clients attempt to join they get an error stating "Required loading" suggesting a missing module. Starting any other mission works fine.

[dcc_support.zip](https://github.com/Kilcekru/dcc/files/12266782/dcc_support.zip)

**Comment by harryer46** [comment]
same issue here
[dcc_support.zip](https://github.com/Kilcekru/dcc/files/12785785/dcc_support.zip)
same issue here 
MP still doesn't work right now
![image](https://github.com/Kilcekru/dcc/assets/26032873/8f55dbb1-e97a-4b76-b1e4-d9f2e7d4bf5d)

**Comment by harryer46** [comment]
found a workaround in the discord:
open the dcc_mission in the editor, save, and it works

**Comment by Kilcekru** [comment]
fixed

**Comment by nabbl** [comment]
Can confirm. Works nicely now. Thx!
